# Generated by Django 4.2.4 on 2023-08-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, null=True, to='employee.qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.salary'),
        ),
    ]
